version: '3.8'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
      - /app/__pycache__
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - data-portal-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://api:8001
    networks:
      - data-portal-network
    depends_on:
      - api

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: tail -f /app/app.log
    volumes:
      - ./backend:/app
    networks:
      - data-portal-network

networks:
  data-portal-network:
    driver: bridge 